# Xavier Bresson

name: deeplearn_course


channels:
  
  - pytorch

dependencies:

  # basic
  - python=3.6
  - numpy
  - mkl
  - ipython
  - jupyter
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - networkx
  - seaborn

  # deep learning
  - pytorch=0.4.1
  - pip:
    - torchvision

